n = 10
(
    SELECT_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_RECONCILIATION_START_DATE,
    GET_RECONCILIATION_END_DATE,
) = range(0, n)