n = 14
(
    SELECT_LANG,
    GET_NAME,
    GET_CONTACT,
    CLICK_LANG,
    ALL_SETTINGS,
    LANG_SETTINGS,
    NAME_SETTINGS,
    PHONE_SETTINGS,
    GET_RECONCILIATION_START_DATE,
    GET_RECONCILIATION_END_DATE,
    GET_CONTACT_VIA_BUTTON,
    GET_PHONE_NUMBER,
    GET_BRANCH,
    SELECT_CABINET,
) = range(0, n)